import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
  <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
         {/* eslint-disable-next-line @next/next/no-css-tags */}
         <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
      </Head>
        <Component {...pageProps} />
       {/* credits */}
       <div className="text-center mt-4">
                <p>
                    <a href="#" target="_top">Master Next JS</a>
                </p>
                <p>
                    <a href="https://github.com/fazrithe" target="_top">Fazrithe</a>
                </p>
            </div>
  </>
  )
}
